services:
  zot:
    build: 
      context: ./zot/
      args:
        R2_ID: 
        R2_BUCKET: 
        R2_ACCESS_KEY: 
        R2_SECRET_KEY: 
        S3_CHUNK_SIZE: 16777216
    networks:
      bug_report:
        aliases:
          - zot
    ports:
      - "5000:5000"

  skopeo:
    build: 
      context: ./skopeo/
    networks:
      bug_report:
        aliases:
          - skopeo
    depends_on:
      - zot

networks:
  bug_report: